artifacts_root: artifacts

data_collection:
  root_dir: "artifacts/data_collection"
  api_key: "key"
  
  # city_info = [
#     {"city": "Mumbai", "lat": 19.0760, "lon": 72.8777},
#     {"city": "Delhi", "lat": 28.6139, "lon": 77.2090},
#     {"city": "Kolkata", "lat": 22.5726, "lon": 88.3639},
#     {"city": "Chennai", "lat": 13.0827, "lon": 80.2707},
#     {"city": "Bangalore", "lat": 12.9716, "lon": 77.5946},
#     {"city": "Hyderabad", "lat": 17.3850, "lon": 78.4867},
#     {"city": "Pune", "lat": 18.5204, "lon": 73.8567},
#     {"city": "Ahmedabad", "lat": 23.0225, "lon": 72.5714},
#     {"city": "Jaipur", "lat": 26.9124, "lon": 75.7873},
#     {"city": "Surat", "lat": 21.1702, "lon": 72.8311}
# ]

# cities_info = [
#     {"city": "Thiruvananthapuram", "lat": 8.5241, "lon": 76.9366},
#     {"city": "Patna", "lat": 25.5941, "lon": 85.1376},
#     {"city": "Lucknow", "lat": 26.8467, "lon": 80.9462},
#     {"city": "Chandigarh", "lat": 30.7333, "lon": 76.7794},
#     {"city": "Bhopal", "lat": 23.2599, "lon": 77.4126}
# ]
  city_info: 
    city: "Kolkata"
    lat: 22.5726
    lon: 88.3639
  start_date: "2021-01-01"
  end_date: "2024-05-31"
  output_file: "artifacts/data_collection"


data_ingestion:
  root_dir: artifacts/data_ingestion # Root directory where data will be stored
  secure_connect_bundle: D:\ML-Projects\Database\secure-connect-aqi-data.zip  # Path to the secure connect bundle for connecting to AstraDB
  username:  # AstraDB username
  password:  # AstraDB password
  keyspace: aqidata  # Keyspace in AstraDB
  table_name: table_final  # List of Table name in AstraDB
  region_name: eu-west-1 # Region name in AstraDB
  output_file: artifacts/data_ingestion/data.csv # Path to save the downloaded data

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv

